### ISSUE TITLE
[BUG] Relative IPs on node VLANs are unresolved

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#1411] opened 2024-10-21 13:36 UTC
### Describe the bug

Assigning a relative IP to a node on a VLAN does not work as (I) expected

### To Reproduce

```netlab create test-topo.yml```

### Expected behavior

n1 should get IP 10.0.0.2/24

### Lab topology

```
---
module: [ vlan ]

vlans:
 v1:
  prefix: 10.0.0.0/24

nodes:
 n1:
  vlans:
   v1:
    ipv4: 2  # Assign relative IP 2 -> this does not work
 
 n2:

links:
- n1:
  n2:
   vlan.trunk:
    v1:
     ipv4: 3   # Assign relative IP 3 -> works
  vlan.trunk: [ v1 ]
```

### Output

```
# Ansible inventory created from ['/home/jvanbemmel/test/vlan-relative-ip.yml', '/home/jvanbemmel/.netlab.yml', 'package:topology-defaults.yml']
#

af:
  ipv4: true
box: generic/ubuntu2004
interfaces:
- ifindex: 1
  ifname: eth1
  libvirt:
    type: tunnel
  linkindex: 1
  name: n1 -> n2
  neighbors:
  - ifname: eth1
    node: n2
  remote_id: 2
  remote_ifindex: 1
  subif_index: 1
  type: p2p
- ifindex: 2
  ifname: eth1.1000
  parent_ifindex: 1
  parent_ifname: eth1
  type: vlan_member
  virtual_interface: true
  vlan:
    access: v1
    access_id: 1000
- bridge_group: 1
  ifindex: 3
  ifname: vlan1000
  ipv4: 2                                         <-- problem is here
  name: VLAN v1 (1000) -> [n2]
  neighbors:
  - ifname: vlan1000
    ipv4: 10.0.0.3/24
    node: n2
  type: svi
  virtual_interface: true
  vlan:
    mode: irb
    name: v1
loopback:
  ifindex: 0
  ifname: lo
  ipv4: 10.0.0.1/32
  neighbors: []
  type: loopback
  virtual_interface: true
mgmt:
  ifname: eth0
  ipv4: 192.168.121.101
  mac: 08:4f:a9:00:00:01
module:
- vlan
vlan:
  max_bridge_group: 1
vlans:
  v1:
    bridge_group: 1
    id: 1000
    ipv4: 2
    mode: irb
    prefix:
      allocation: id_based
      ipv4: 10.0.0.0/24
```

### Version

'dev' branch

**Comment by jbemmel** [comment] 2024-10-21 13:40
This also triggered a related issue when using ```ipv4: 1``` on a node VLAN
```
 msg: 'AnsibleUndefinedVariable: ''dict object'' has no attribute ''_parent_intf'''
```

in the EOS initial template - apparently this leads to a code path on which ```_parent_intf``` is not set

**Comment by ipspace** [comment] 2024-10-21 13:40
I agree this should work on **irb** VLANs. Let me check where we should copy **ipv4** to node interfaces but don't.

**Comment by ipspace** [comment] 2024-10-21 13:42
> in the EOS initial template - apparently this leads to a code path on which `_parent_intf` is not set

Because **ipv4** is not a string but a number. _parent_intf should be set for interfaces where **ipv4** is set to True.

**Comment by ipspace** [comment] 2024-10-23 10:12
Found the probable root cause: node VLAN data is not copied into interface data before the link transformation starts but is merged with node interface data after that.

However, if we copy all the VLAN data into interface data, we'll get the VLAN module yelling that it's ignoring interface data when creating the SVI interface, so it looks like we have to copy only a small subset of data (**ipv4**, **ipv6** and **gateway**)

**Closed** 2024-10-24 05:01 UTC
Labels: bug
