### ISSUE TITLE
[BUG] Global and node level 'gateway' attributes not propagated to interfaces

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#1413] opened 2024-10-21 15:02 UTC
### Describe the bug
In the given topology, the intent is to make ```n1``` a gateway on VLAN v1

### To Reproduce
```netlab create test.yml```

### Expected behavior
n1 should be configured as VRRP gateway

### Lab topology

```
module: [gateway,vlan]
gateway.protocol: vrrp

vlans:
 v1:

nodes:
 n1:
  vlans:
   v1:
    gateway: True
```

### Output
```
  File "/home/jvanbemmel/netlab/netsim/modules/gateway.py", line 39, in check_protocol_support
    gw_proto = intf.gateway.protocol                                  # We're asuming someone else did a sanity check on this value
               ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'bool' object has no attribute 'protocol'

```

### Version

dev branch

### Additional context
Suggested fix, add in gateway.py ```check_protocol_support``` line 36
```
    if intf.gateway is True:                                          # Expand global and node specific gateway parameters
      intf.gateway = topology.gateway + node.get('gateway',{})
```

**Comment by ipspace** [comment] 2024-10-21 17:47
It should be noted we never promised that you can enable a gateway protocol on a single node. It was designed to be enabled on a link, and all nodes on the link would run that protocol: https://netlab.tools/module/gateway/#link-parameters

One could argue this is a FAD, but even then the whole thing should not crash. One could also "fix" the crash with stricter requirements on interface **gateway** attribute (instead of https://github.com/ipspace/netlab/blob/dev/netsim/modules/gateway.yml#L28).

However, let's say I tentatively agree there might be a crazy niche case (that I can't figure out at the moment) where you would want to run VRRP (or whatever) on one node (with **gateway** module) but not on another one (also using **gateway** module for some other link).

Will look into how this could get fixed without too many hacks.

**Comment by jbemmel** [comment] 2024-10-21 19:00
The topology was minimized to simplify the discussion, but the full use case is having a bunch of switches forwarding that vlan across the network, with only a subset of them acting as gateway. The gateway properties would be defined once on the VLAN - for consistency - and then selected nodes would have ```gateway: True```

**Comment by ipspace** [comment] 2024-10-22 11:18
> The full use case is having a bunch of switches forwarding that vlan across the network, with only a subset of them acting as gateway.

Can't you use the **gateway** module just on that subset? It was not designed to be used selectively (per-node).

**Comment by jbemmel** [comment] 2024-10-22 11:30
> Can't you use the **gateway** module just on that subset? It was not designed to be used selectively (per-node).

I'm using it to model a network that has "evolved" over time, with different design paradigms. Some nodes are gateways on some VLANs but not all of them, etc.

**Comment by ipspace** [comment] 2024-10-22 12:58
I just verified this is not VLAN-related. The minimum topology that crashes _netlab_ is this:

```
module: [ gateway ]

gateway.protocol: vrrp

nodes:
  r1:

links:
- r1:
    gateway: True
```

The crash is obviously unacceptable. How I'm going to fix it depends on the complexity of the fix. Fortunately, (unlike device vendors) we don't have to increase software complexity to support the byproducts of network evolution.

**Comment by ipspace** [comment] 2024-10-22 12:59
> Some nodes are gateways on some VLANs but not all of them, etc.

The obvious next question would be "and why are they attached to those other VLANs at all?"

**Comment by ipspace** [comment] 2024-10-23 04:07
OK, back to our regular programming ;) The root cause of the whole thing is that the gateway-related stuff is not triggered on the links because the **gateway** parameter is only present on interfaces.

This means we would have to:

A) before link transformation

* Propagate **gateway: True** from interfaces to links and remove it from interfaces
* When we do that, set **gateway: False** on all other interfaces for nodes with the **gateway** module

B) in the final gateway code

* Remove **gateway: False** from interfaces and skip the gateway processing on those nodes.

**Closed** 2024-10-26 08:19 UTC
Labels: bug
